#!/data/data/com.termux/files/usr/bin/python3.9

from __future__ import unicode_literals
from youtubesearchpython import VideosSearch

import os
import sys
import signal
import time
import copy
import random
import validators
import subprocess
from threading import Thread

NEWLINE='\n'

HOME_DIR=os.path.expanduser('~')

TMP_DIR=HOME_DIR+'/.audio-engine'

if not os.path.isdir(TMP_DIR):
    os.mkdir(TMP_DIR)

AUDIO_CACHE_DIR=TMP_DIR+'/'+'cache'
AUDIO_DOWNLOAD_CACHE_DIR=TMP_DIR+'/'+'download'

if not os.path.isdir(AUDIO_CACHE_DIR):
    os.mkdir(AUDIO_CACHE_DIR)

if not os.path.isdir(AUDIO_DOWNLOAD_CACHE_DIR):
    os.mkdir(AUDIO_DOWNLOAD_CACHE_DIR)

keywords=None
url=None
FILE_PATH=None
DIR_PATH=None
loop=False
max_thread=10
shuffle=False
audio_format="opus"
now_playing=None
thread_count=0
new=False

history=[]
loaded=[]
queue=[]

def basename(path):
    return path.split('/')[-1]

usage_message=f"""usage: {basename(sys.argv[0])} [options...]
{basename(sys.argv[0])} --help for more info"""

help_message=f"""{usage_message.split(NEWLINE)[0]}

OPTIONS

    (-h | --help)
    show this help page

    (-k | --search) <keywords>
    search for online audio that matches <keywords>

    (-u | --url) <link>
    load media from <link>

    (-f | --file) <filepath>
    load media file in <filepath>

    (-F | --dir | --folder) <dirpath>
    load media files in <dirpath>

    (-s | --shuffle)
    toggle on shuffle

    (-l | --loop)
    loop playlist

    (-n | --new | --renew)
    renew online videos instead of loading cached ones

    (-t | --thread) <number>
    set maximum number streaming thread to <number>

INTERACTIVE COMMANDS
    
    (clear)
    trigger clear screen

    (show) <param>
    show detail of given param:
        
        <<track | info | status>>
        display details of current track

        <<help>>
        display help page

        <<usage>>
        display usage

        <<queue>>
        display a list of queued entry

        <<loaded>>
        display a list of loaded entry

        <<history>>
        display a list of tracks in history

        <<shuffle>>
        display shuffle state (True/False)

        <<loop>>
        display loop state (True/False)

        <<new>>
        display new state (True/False)

    (play | resume)
    resume paused track, if any

    (search | browse) <keywords>
    search track online by <keywords>

    (url | link) <url>
    search track online by <url>

    (stop | next)
    skip current track

    (pause)
    pause current track

    (pwd)
    print current working directory

    (local) <pathname>
    search and play local files in <pathname>

    (file) <filepath>
    search and play local file in <filepath>

    (folder | dir | directory) <dirpath>
    search and play local files in <dirpath>

    (shuffle) <param>
    Toggle shuffle to <param>

        <<on>>

        <<off>>

    (loop) <param>
    Toggle loop to <param>

        <<on>>

        <<off>>

    (new) <param>
    Toggle new to <param>

        <<on>>

        <<off>>

    (shutdown | bye | quit |exit)
    Close and exit program

DEFAULTS

    shuffle         :   {shuffle}

    loop            :   {loop}

    new online file :   {new}

    max thread      :   {max_thread}
"""

def clear():
    os.system('clear')

def showUsage():
    os.system(f"cat <<< '{usage_message}'")

def showHelp():
    os.system(f"less <<< '{help_message}'")

def fileNotfound(path):
    print(f"'{path}': file not found")

def dirNotfound(path):
    print(f"'{path}': directory not found")

def shellFormat(arg):
    arg=str(arg)

    special=['\\','/',' ','~','`','#','$','&','*','(',')','|','[',']','{','}',';','\'','\"','<','>','?','!']

    for c in special:
        arg=arg.replace(c, '\\'+c)

    empty=True
    for c in arg:
        if c!=' ':
            empty=False
            break

    if empty:
        arg='\'\''

    return arg

def search(key):
    global queue

    search_limit=10

    response=None

    while True:
        try:
            response=VideosSearch(key, limit=search_limit).result()
            break
        except:
            time.sleep(1)
            continue

    for i in range (search_limit):
        try:
            result=response['result'][i]
            video_link=result['link']

            if not result['duration']: raise

            queue.append(video_link)

            return
        except:
            continue
    

def download(url):
    global loaded, ydl_opts, thread_count, AUDIO_CACHE_DIR, AUDIO_DOWNLOAD_CACHE_DIR

    while True:

        name=os.popen(f"yt-dlp --simulate --get-title {shellFormat(url)} 2> /dev/null").read().rstrip('\n')
        name=name.replace('/',' ')

        if (not name): continue
        
        file_exist=os.popen(f"if [ -f {shellFormat(AUDIO_DOWNLOAD_CACHE_DIR+'/'+name)} ]; then echo -n true; else echo -n false; fi").read()

        if new or file_exist=='false':
            output=f"{AUDIO_DOWNLOAD_CACHE_DIR}/{name}.%(ext)s.%(ext)s"

            os.popen(f"yt-dlp --extract-audio --audio-quality 0 --quiet --output {shellFormat(output)} {shellFormat(url)} 2> /dev/null").read()

            try:
                output_name=[file for file in os.listdir(AUDIO_DOWNLOAD_CACHE_DIR) if name in file][0]
                
                origin_path=AUDIO_DOWNLOAD_CACHE_DIR+'/'+output_name
                destination_path=AUDIO_DOWNLOAD_CACHE_DIR+'/'+name

                os.system(f"mv {shellFormat(origin_path)} {shellFormat(destination_path)} 2> /dev/null")
            except:
                continue

        loaded.append(AUDIO_DOWNLOAD_CACHE_DIR+'/'+name)

        thread_count-=1

        break

def loader():
    global queue, loaded, thread_count, AUDIO_CACHE_DIR, AUDIO_DOWNLOAD_CACHE_DIR

    threads=[]

    while True:
        if shuffle and queue:
            index=random.randint(0, len(queue)-1)
            queue[0], queue[index] = queue[index], queue[0]
        if queue:
            if validators.url(queue[0]):
                if thread_count==max_thread:
                    if len(queue)>=2:
                        queue[0], queue[-1] = queue[-1], queue[0]
                        continue

                thread=Thread(target=download, args=(queue[0],))
                threads.append(thread)
                thread.start()
                
                thread_count+=1
                

            elif os.path.isfile(queue[0]):
                os.system(f'cp {shellFormat(queue[0])} {shellFormat(AUDIO_CACHE_DIR)}')
                loaded.append(queue[0])
            else:
                pass
            queue.remove(queue[0])
        else:
            time.sleep(1)
            continue

        time.sleep(1)

def player():
    global now_playing, loaded, history

    while True:
        now_playing=os.popen('termux-media-player info').read().rstrip('\n')
        if now_playing=='No track currently!':
          now_playing=None

        else:
            time.sleep(1)
            continue

        if loaded and not now_playing:
            os.system(f"termux-media-player play {shellFormat(loaded[0])} >/dev/null")
            history.append(loaded[0])
            loaded.remove(loaded[0])  
        else:
            time.sleep(1)
            continue

        time.sleep(1)

def looper():
    global queue, loaded, history, now_playing

    while True:
        if loop and history and not loaded and not queue:
            if not now_playing:
                try:
                    if (shuffle):
                        item=random.choice(history)
                    else:
                        item=history[0]
                    loaded.append(item)
                    history.remove(item)
                except:
                    time.sleep(1)
                    continue
            else:
                time.sleep(1)
                continue
        else:
            time.sleep(1)
            continue

        time.sleep(1)


def close(sig=None,frame=None):
    global AUDIO_CACHE_DIR

    clear()

    print('Clearing cache...')
    for file in os.listdir(AUDIO_CACHE_DIR):
        os.system(f"rm {shellFormat(AUDIO_CACHE_DIR+'/'+file)}")

    print('Stopping media player...')
    os.system("termux-media-player stop")

    os._exit(0)

def signalHandler():
    signal.signal(signal.SIGINT, close)
    signal.signal(signal.SIGTERM, close)

signalHandler()

shift=False
for i in range(1, len(sys.argv)):
    if shift:
        shift=False
        continue

    if sys.argv[i]=='-h' or sys.argv[i]=='--help':
        showHelp()
        exit(0)

    elif sys.argv[i]=='-k' or sys.argv[i]=='--search':
        try:
            keywords=sys.argv[i+1]
        except:
            showUsage()
            exit(1)

        shift=True
        continue

    elif sys.argv[i]=='-u' or sys.argv[i]=='--url':
        try:
            url=sys.argv[i+1]
            if not validators.url(url):
                raise
        except:
            showUsage()
            exit(1)

        shift=True
        continue

    elif sys.argv[i]=='-f' or sys.argv[i]=='--file':
        try:
            FILE_PATH=sys.argv[i+1]
            if not os.path.isfile(FILE_PATH):
                print(f"'{FILE_PATH}': file not found")
                raise
        except:
            showUsage()
            exit(1)

        shift=True
        continue

    elif sys.argv[i]=='-F' or sys.argv[i]=='--dir' or sys.argv[i]=='--folder':
        try:
            DIR_PATH=sys.argv[i+1]
            if not os.path.isdir(DIR_PATH):
                print(f"'{DIR_PATH}': directory not found")
                raise
        except:
            showUsage()
            exit(1)

        shift=True
        continue

    elif sys.argv[i]=='-l' or sys.argv[i]=='--loop':
        loop=True
        continue

    elif sys.argv[i]=='-s' or sys.argv[i]=='--shuffle':
        shuffle=True
        continue

    elif sys.argv[i]=='-n' or sys.argv[i]=='--new' or sys.argv[i]=='--renew':
        new=True
        continue

    elif sys.argv[i]=='-t' or sys.argv[i]=='--thread':
        try:
            max_thread=int(sys.argv[i+1])
        except:
            showUsage()
            exit(1)

        shift=True
        continue

    else:
        showUsage()
        exit(1)

if keywords:
    Thread(target=search, args=(keywords,)).start()

if url:
    Thread(target=search, args=(url,)).start()

if FILE_PATH:
    queue.append(FILE_PATH)

if DIR_PATH:
    dir_list=os.listdir(DIR_PATH)
    for file in dir_list:
        queue.append(DIR_PATH+'/'+file)

loader_task=Thread(target=loader)
loader_task.start()

player_task=Thread(target=player)
player_task.start()

looper_task=Thread(target=looper)
looper_task.start()

clear()

while True:
    cmd=input('\033[1;3;33m>>> \033[0m')

    cmd=cmd.strip(' ')

    original_cmd=cmd

    cmd=cmd.replace('\t', ' ')
    cmd=cmd.replace('\n', ' ')

    cmd=cmd.split(' ')

    while '' in cmd:
        cmd.remove('')

    param=' '.join(cmd[1::1])
    
    cmd=' '.join(cmd[0:1:1])

    if not cmd:
        continue

    elif cmd=='clear':
        clear()

    elif cmd=='show':
        if param=='track' or param=='info' or param=='status':
            print(now_playing)

        elif param=='help':
            showHelp()

        elif param=='usage':
            showUsage()

        elif param=="queue":
            queue_page=''
            for entry in queue:
                if validators.url(entry)==True:
                    queue_page+=entry+'\n'
                else:
                    queue_page+=basename(entry)+'\n'

            queue_page=queue_page.rstrip('\n')

            queue_page=queue_page.replace('(','<')
            queue_page=queue_page.replace(')','>')
            queue_page=queue_page.replace('\'','-')
            queue_page=queue_page.replace('\"','-')
            os.system(f"cat -n <<< '{queue_page}' | less")

        elif param=="loaded":
            loaded_page=''
            for entry in loaded:
                loaded_page+=basename(entry)+'\n'
            
            loaded_page=loaded_page.rstrip('\n')
            
            loaded_page=loaded_page.replace('(','<')
            loaded_page=loaded_page.replace(')','>')
            loaded_page=loaded_page.replace('\'','-')
            loaded_page=loaded_page.replace('\"','-')

            os.system(f"cat -n <<< '{loaded_page}' | less")

        elif param=="history":
            history_page=''
            for entry in history:
                history_page+=basename(entry)+'\n'
            history_page=history_page.rstrip('\n')

            history_page=history_page.replace('(','<')
            history_page=history_page.replace(')','>')
            history_page=history_page.replace('\'','-')
            history_page=history_page.replace('\"','-')

            os.system(f"cat -n <<< '{history_page}' | less")

        elif param=="shuffle":
            print(shuffle)

        elif param=="loop":
            print(loop)

        elif param=="new":
            print(new)

        else:
            continue

    elif cmd=='play' or cmd=='resume':
        os.popen('termux-media-player play > /dev/null').read()

    elif cmd=='search' or cmd=='browse':
        if param:
            Thread(target=search, args=(param,)).start()
        else:
            continue

    elif cmd=='url' or cmd=='link':
        if param and validators.url(param):
            Thread(target=search, args=(param,)).start()
        else:
            continue

    elif cmd=='stop' or cmd=='next':
        os.popen('termux-media-player stop >/dev/null').read()

    elif cmd=='pause':
        os.popen('termux-media-player pause > /dev/null')

    elif cmd=='pwd':
        os.system('pwd')

    elif cmd=='local':
        if param:
            local_path=original_cmd[len(cmd)+1::1]
            if os.path.isfile(local_path):
                queue.append(local_path)
            elif os.path.isdir(local_path):
                for file in os.listdir(local_path):
                    queue.append(local_path+'/'+file)
            else:
                continue
        else:
            continue

    elif cmd=='file':
        if param:
            local_path=original_cmd[len(cmd)+1::1]
            if os.path.isfile(local_path):
                queue.append(local_path)
            else:
                continue
        else:
            continue

    elif cmd=='folder' or cmd=='dir' or cmd=='directory':
        if param:
            local_path=original_cmd[len(cmd)+1::1]
            if os.path.isdir(local_path):
                for file in os.listdir(local_path):
                    queue.append(local_path+'/'+file)
            else:
                continue
        else:
            continue

    elif cmd=='shuffle':
        if param=='on':
            shuffle=True
        elif param=='off':
            shuffle=False
        else:
            continue

    elif cmd=='loop':
        if param=='on':
            loop=True
        elif param=='off':
            loop=False
        else:
            continue

    elif cmd=='new':
        if param=='on':
            new=True
        elif param=='off':
            new=False
        else:
            continue

    elif cmd=='shutdown' or cmd=='bye' or cmd=='quit' or cmd=='exit':
        close()

    else:
        print(f"{cmd}: invalid command")
        continue
